kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: my-laravel
          image: topkee-php:8.0-apache-bullseye
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
